name: BranchWorkflow

on:
  push:
    branches-ignore: [main]

jobs:
  test:
    name: TestStage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ^1.23

      - name: Check Go
        run: go version

      - name: Test
        run: make tests
