name: PullRequestWorkflow

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: LintStage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ^1.23

      - name: Check Go
        run: go version

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.63.4
